CREATE TABLE tb_users(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    password VARCHAR(512) NOT NULL,
    photo VARCHAR(512),
    register TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
